// <auto-generated by="the Blazor I18n Text compiler" />
namespace EsmaulHusna.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About"</summary>
        public string About;

        /// <summary>"esmaulhusna-en.csv"</summary>
        public string FileName;

        /// <summary>"Prophet Muhammad (ﷺ) said, “Allah has ninety-nine names, i.e. one-hundred minus one, and whoever knows them will go to Paradise."</summary>
        public string Hadis;

        /// <summary>"(Sahih Bukhari 50:894)"</summary>
        public string HadisSrc;

        /// <summary>"99 Names of Allah (Al Asma Ul Husna) Memorization Application"</summary>
        public string Header;

        /// <summary>"Home"</summary>
        public string HomePage;

        /// <summary>"99 Names of Allah"</summary>
        public string SiteName;
    }
}
